### ISSUE TITLE
Proposal for refactor of Menu YAML file

### ISSUE THREAD

**Issue by djmoffat** [chrisfleming/MassCatering#17]
This issue is to discuss the proposal of a new YAML file structure, to facilitate

- Easy to present menu overview
- allow adding _notes_ section to individual recipes
- allow adding _no_print_ flag to menu items
- allow for menu ordering to take place

The current example menu YAML file structure is:
```
recipe_1:
      day_1:  num_people
      day_2: num_people
recipe_2:
      day_1:  num_people
      day_2: num_people
...
```

New proposed example structure

```
day_1:
      meal_1:  
            recipe_1: num_people
                  notes: Note to show at bottom of markdown recipe file
            recipe_2: num_people
            recipe_3: num_people
                  no_print: True
      meal_2:  
            recipe_1: num_people
                  notes: Note to show at bottom of markdown recipe file
            recipe_4: num_people
                  notes: Note to show at bottom of markdown recipe file
            recipe_5: num_people
...
```

The ability to add notes to a specific recipe will increase the flexibility for one-off recipe changes (ie. Make mash potato vegan) rather than having to create many copies of very similar recipes.

The no-print value is not required, but may save producing a .md file for generic items ie. generic hostel list, or per-person per day items.

Thoughts and opinions welcome
